version: "3.8"
services:
  db:
    image: postgres:14
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file:
      - .env
          
  backend:
    image: ciplay-task-backend:latest
    depends_on:
      - db
    env_file:
      - .env
    build:
      context: ./backend
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}

volumes:
  pg-data:

